# Setup
title: Pmj9384
description: The homepage of minjae Park
url: https://pmj9384.github.io
avatar: /assets/avatar.jpg
paginate: 5
permalink: pretty
cover_image: /bg.jpeg

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - scripts/
  - not-pure-poole.gemspec

# Optimize Jekyl SEO Tag
twitter:
  username: Pmj9384hub
  card: summary
logo: logo.png
social:
  name: minjae Park
  links:
    - https://twitter.com/pmj9384
    - https://github.com/pmj9384
google_site_verification: xxxxx
lang: en

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# google_analytics: UA-000000-0

# Replace this value and uncomment to enable Disqus
comments:
 provider: "disqus"
 disqus: 
    shortname: "pmj9384-github-io"

# Specify the author for blog posts
author:
  name: minjae Park
  url: https://github.com/pmj9384/
  email: pmj9384@gmail.com

# Analytics
analytics:
  provider    : "google"
                # false (default), " google-universal", "google-gtag","custom"
  google:
    tracking_id   : "{UA-273287017-1}"
    anonymize_ip  : # true, false (default)